config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  namespace :admin do
    root "static_pages#home"
    resources :categories, except: :show
    resources :users
    resources :books, only: [:index, :show]
  end
  resources :users, except: [:destroy, :index] do
    resources :following, only: :index
    resources :followers, only: :index
  end
  resources :books, only: [:index, :show] do
    resources :reviews
  end
  resources :relationships, only: [:create, :destroy]
  resources :books, only: [:index, :show]
  resources :favourites, only: [:create, :destroy]
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category

  has_many :reviews, dependent: :destroy
  has_many :passive_rates, class_name: Rating.name, foreign_key: :book_id,
    dependent: :destroy
  has_many :raters, through: :passive_rates, source: :user

  mount_uploader :image, PictureUploader

  VALID_DATE_REGEX = /\A\d{4}\-(?:0?[1-9]|1[0-2])\-(?:0?[1-9]|[1-2]\d|3[01])\z/i
  validates :title, presence: true,
    length: {maximum: Settings.maximum_name_email}, uniqueness: true
  validates :description, presence: true
  validates :publish_date, presence: true, format: {with: VALID_DATE_REGEX}
  validates :author, presence: true

  scope :more_rate, -> do
    order(rating: :desc).limit Settings.limit_book
  end
  scope :show_newest, -> do
    order(created_at: :desc).limit Settings.limit_book
  end
  scope :filter_newest, ->{order created_at: :desc}
  scope :search, ->search do
    where "title LIKE ? OR author LIKE ?", "%#{search}%", "%#{search}%"
  end
  scope :search_by_category, ->category_id do
    where category_id: category_id
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :verify_admin_access?
  before_action :book_find_by, except: [:index, :new, :create]

  def index
    @books = Book.filter_newest.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def show
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new book_params
    if @book.save
      flash[:success] = t "admin.books.created_book"
      redirect_to admin_books_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update book_params
      flash[:success] = t "admin.books.updated_book"
      redirect_to @book
    else
      render :edit
    end
  end

  def destroy
    if @book.destroy
      flash[:success] = t "admin.books.deleted_book"
    else
      flash[:success] = t "admin.books.undeleted_book"
    end
    redirect_to admin_book_path
  end

  private
  def book_params
    params.require(:book).permit :title, :description, :publish_date, :author, :image,
      :page, :rating, :category_id
  end

  def load_book
    @book = Book.find_by id: params[:id]
    unless @book
      flash[:danger] = t "admin.cant_found_book"
      redirect_to admin_book_path
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :logged_in_user, except: [:show, :index]
  before_action :load_book, only: :show

  def index
    @books = Book.filter_newest.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def show
    if logged_in?
      @review = @book.reviews.build
    end
    @reviews = @book.reviews.includes(:user, comments: :user).newest
      .paginate page: params[:page], per_page: Settings.per_page
  end

  private
  def load_book
    @book = Book.find_by id: params[:id]
    unless @book
      flash[:warning] = t "app.controllers.error_not_exits"
      redirect_to root_url
    end
  end
end

app/views/admin/books/_form_book.html.erb
<%= form_for [:admin, @book] do |f| %>
  <%= render "shared/error_messages", object: @book %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div>
    <%= f.label :publish_date %>
    <%= f.text_field :publish_date, class: "form-control" %>
  </div>
  <div>
    <%= f.label :author %>
    <%= f.text_field :author, class: "form-control" %>
  </div>
  <div>
    <%= f.label :image %>
    <%= f.text_field :image, class: "form-control" %>
  </div>
  <div>
    <%= f.label :page %>
    <%= f.text_field :page, class: "form-control" %>
  </div>
  <div>
    <%= f.label :rating %>
    <%= f.text_field :rating, class: "form-control" %>
  </div>
  <div>
    <%= f.label :category_id %>
    <%= f.select :category_id, get_data_category, include_blank: true %>
  </div>
  <div>
    <%= f.submit yield :button_text, class: "btn btn-primary",
      id: "btn_book" %>
    <%= link_to t("cancel"), :back, class: "btn btn-default" %>
  </div>
<% end %>

app/views/admin/books/edit.html.erb
<% provide :title, t("admin.books.view_title_create_book") %>
<% provide :button_text, t("admin.books.btn_created_book") %>
<% if verify_admin_access? %>
  <h1><%= t("admin.books.view_title_create_book") %></h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="form-books">
        <%= render "form_book" %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/books/index.html.erb
<%= will_paginate @books %>
<% @books.each do |book| %>
  <div class="well">
    <div class="media">
      <%= link_to get_image(book, "media-object"), book, class: "pull-left" %>
      <div class="media-body">
        <h4 class="media-heading"><%= book.title %></h4>
          <p class="text-right"><%= book.author %></p>
          <p><%= truncate(book.description, length: Settings.limit_len) %>
          <%= link_to t("admin.books.read_more"), book %></p>
          <ul class="list-inline list-unstyled">
          <li><span><i class="glyphicon glyphicon-calendar"></i> <%= book.publish_date %> </span></li>
          <li>|</li>
          <span><i class="glyphicon glyphicon-comment"></i></span>
          <li>|</li>
          <li>
            <% i = Settings.minimum_rate %>
            <% while i <= book.rating.floor do %>
              <span class="glyphicon glyphicon-star"></span>
              <% i += Settings.minimum_rate %>
            <% end %>
            <% if book.rating.floor < Settings.max_rate %>
              <% j = Settings.minimum_rate %>
                <% while j <= Settings.max_rate - book.rating.floor do %>
                  <span class="glyphicon glyphicon-star-empty"></span>
                  <% j += Settings.minimum_rate %>
                <% end %>
            <% end %>
            <label><%= book.rating %>-</label>
          </li>
            <%= link_to t("admin.books.edit"), edit_admin_book_path book %>
          <li>
            <%= link_to t("admin.books.delete"), [:admin, book], method: :delete,
              data: {confirm: t("admin.books.are_you_sure")} %></li>
          <li>
            <span><i class="fa fa-facebook-square"></i></span>
            <span><i class="fa fa-twitter-square"></i></span>
            <span><i class="fa fa-google-plus-square"></i></span>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <hr>
<% end %>
<%= will_paginate @books %>

app/views/admin/books/new.html.erb
<% provide :title, t("admin.books.view_title_create_book") %>
<% provide :button_text, t("admin.books.btn_created_book") %>
<% if verify_admin_access? %>
  <h1><%= t "admin.books.view_title_create_book" %></h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="form-books">
        <%= render "form_book" %>
      </div>
    </div>
  </div>
<% end %>