config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  namespace :admin do
    root "static_pages#home"
    resources :categories, except: :show
    resources :users
    resources :books, only: [:index, :show]
  end
  resources :users, except: [:destroy, :index] do
    resources :following, only: :index
    resources :followers, only: :index
  end
  resources :books, only: [:index, :show] do
    resources :reviews
  end
  resources :relationships, only: [:create, :destroy]
  resources :books, only: [:index, :show]
  resources :favourites, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t "views.layouts.footer.title" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("views.layouts.footer.about"), about_path %></li>
      <li><%= link_to t("views.layouts.footer.contact"), contact_path %></li>      
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("views.layouts.header.logo"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("views.layouts.header.home"), root_path %></li>
        <li><%= link_to t("views.layouts.header.help"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("views.users"), "#" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t "views.account" %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("views.profile"), current_user %></li>
              <li><%= link_to t("views.settings"), "#" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("views.logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("views.layouts.header.login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
                                              "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>